(function(g){var window=this;'use strict';var Y3=function(a){a.ea("cardstatechange",a.xj()&&a.uo()?1:0)},Z3=function(a,b){var c=g.Ha(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},aab=function(a){var b=g.Ml(a);
a=g.Pl(a);return new g.vl(b.x,b.y,a.width,a.height)},bab=function(a){return Math.pow(a,3)},cab=function(a){return 3*a*a-2*a*a*a},b4=function(a){a=g.Ka(a);
delete $3[a];g.Tc($3)&&a4&&a4.stop()},eab=function(){a4||(a4=new g.io(function(){dab()},20));
var a=a4;a.isActive()||a.start()},dab=function(){var a=g.Qa();
g.Dc($3,function(b){fab(b,a)});
g.Tc($3)||eab()},c4=function(a,b,c,d){g.Co.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.T=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},fab=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;gab(a,a.progress);1==a.progress?(a.j=0,b4(a),a.onFinish(),a.zq()):a.Zc()&&a.jI()},gab=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.T[c]-a.u[c])*b+a.u[c]},hab=function(a,b){g.eb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},d4=function(a,b,c,d,e){c4.call(this,b,c,d,e);
this.element=a},iab=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
d4.call(this,a,b,c,d,e)},jab=function(a){g.D.call(this);
this.u=a||window;this.j=[]},e4=function(a){return a.baseUrl||null},f4=function(a,b){return g.zm(g.Eg(a,b),function(c){return!!c})},kab=function(a,b,c){function d(R){var ba=R.hovercardButton;
if(!ba)return null;ba=ba.subscribeButtonRenderer;if(!ba)return null;var N=f(ba.unsubscribedButtonText),sa=f(ba.subscribedButtonText);if(ba.subscribed){var la=f(ba.subscriberCountWithUnsubscribeText);var va=f(ba.subscriberCountText)}else la=f(ba.subscriberCountText),va=f(ba.subscriberCountWithSubscribeText);var Ea=null;if(R.signinEndpoint){Ea=Z3(R,"signinEndpoint","webNavigationEndpointData","url");if(!Ea){var Va,Ma;Ea=null==(Ma=g.M(null==(Va=ba.signInEndpoint)?void 0:Va.commandMetadata,g.T2))?void 0:
Ma.url}if(!Ea)return null}return N&&(sa||Ea)?{subscribed:ba.subscribed,subscribeText:N,subscribeCount:la,unsubscribeText:sa,unsubscribeCount:va,enabled:ba.enabled,signinUrl:Ea,classic:R.useClassicSubscribeButton}:null}
function e(R){if(R){var ba=[],N=R.videoId;N&&ba.push("v="+N);(N=R.playlistId)&&ba.push("list="+N);(R=R.startTimeSeconds)&&ba.push("t="+R);return"/watch?"+ba.join("&")}}
function f(R){if(!R)return null;var ba=R.simpleText;return ba?ba:R.runs?g.Eg(R.runs,function(N){return N.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,w=null,x=null,z=!1,B=null,C=null,G=null,F=null,K=null,P=null;if("VIDEO"===h)g.M(l,g.nJ)?m=g.M(l,g.nJ).url:(P=g.M(l,g.lJ),m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.M(l,g.nJ)?m=g.M(l,g.nJ).url:(P=g.M(l,g.lJ),m=e(P)),n=!1,q=a,w=f(b.playlistLength);else if("CHANNEL"===
h){if(z=Z3(l,"browseEndpoint","browseId"))x=z,m="/channel/"+x;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):C=f(b.subscribersText)}else"WEBSITE"===h?((G=Z3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(K=f(b.additionalFeesText)),(n=Z3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=Z3(b,"title","accessibility","accessibilityData","label");var Q=b.endpoint?b.endpoint.clickTrackingParams:null,
Y="";if(b.metadata){var V=f(b.metadata);V&&(Y=V)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Y,callToAction:f(b.callToAction),lS:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,SB:p,playlistLength:w,channelId:x,subscribeButton:B,subscribersText:C,isSubscribe:z,Bt:m||null,T2:n,sessionData:Q?{itct:Q}:null,Q7:q,uA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:f4(b.impressionUrls||[],e4),I2:f4(b.hovercardShowUrls||[],e4),clickUrls:f4(l.loggingUrls||[],e4),visualElement:g.oC(b.trackingParams),productPrice:F,additionalFeesText:K,watchEndpoint:P||null}},lab=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:f4(a.impressionUrls||[],e4),elements:f4(a.elements||[],function(d,e){return kab(b,d,e)})};
a.trackingParams&&(c.visualElement=g.oC(a.trackingParams));return c},mab=function(a){g.rR.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Y=!0;this.I=0;a=a.V();this.T=g.SH(a)||"profilepage"===a.Fa;this.ma=a.experiments.jb("web_rounded_thumbnails");this.events=new g.OF(this);g.E(this,this.events);this.events.S(this.player,g.MB("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.NB("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Db);this.events.S(window,"focus",this.D6);this.load();var b=g.Fe("STYLE");(g.we("HEAD")[0]||
document.body).appendChild(b);g.bb(this,function(){g.Ne(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},nab=function(a){return a.player.getVideoData().D?"current":a.T?"new":"current"},g4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},oab=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=lab(f,nab(a))));h4(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.Aw;d&&(c.postParams={ad_tracking:d});if(b=g.gCa(b))if(b=g.Kd(b),b=g.Hd(b))a.B=g.yw(b,c)},h4=function(a,b,c){c=void 0===c?!0:c;
a.player.dg("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&pab(a);c=[];d=new g.KB(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().u||(a.u=new g.U({G:"div",K:"ytp-ce-shadow"}),g.IQ(a.player,a.u.element,4),a.C=new g.lO(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=qab(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.IQ(a.player,f.element,4);var h=new g.KB(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);rab(a,f,e)}else g.oB(new g.ux("buildEndscreenElement null",
e))}a.player.Pe(c);a.Db()}},pab=function(a){var b=g.rC(),c=g.sC();
c&&b&&a.endscreen.visualElement&&g.dw(g.yM)(void 0,c,b,a.endscreen.visualElement)},qab=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ia:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-covering-image",X:i4(b)},{G:"div",K:"ytp-ce-covering-shadow-top"},{G:"a",K:"ytp-ce-covering-overlay",X:{href:j4(a,b.Bt),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Go(b.title||"")},qa:b.title},{G:"div",K:b.SB?"ytp-ce-live-video-duration":"ytp-ce-video-duration",qa:b.videoDuration||
void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={G:"div",Ia:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-covering-image",X:i4(b)},{G:"div",K:"ytp-ce-covering-shadow-top"},{G:"a",K:"ytp-ce-covering-overlay",X:{href:j4(a,b.Bt),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Go(b.title||"")},qa:b.title},{G:"div",K:"ytp-ce-playlist-count",W:[{G:"div",K:"ytp-ce-playlist-icon"},
{G:"div",K:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={G:"div",Ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-expanding-overlay",W:[{G:"div",K:"ytp-ce-expanding-overlay-hider"},{G:"div",K:"ytp-ce-expanding-overlay-background"},{G:"div",K:"ytp-ce-expanding-overlay-content",W:[{G:"div",
K:"ytp-ce-expanding-overlay-body",W:[{G:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{G:"a",Ia:["ytp-ce-channel-title","ytp-ce-link"],X:{href:j4(a,b.Bt),target:"_blank",tabindex:"-1",dir:g.Go(b.title||"")},qa:b.title},b.subscribeButton?{G:"div",K:"ytp-ce-subscribe-container",W:[{G:"div",K:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",K:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{G:"div",Ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
qa:b.metadata}:""]}]}]}]},{G:"div",K:"ytp-ce-expanding-image",X:i4(b)}]};c=new g.U(c);var d=g.xe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.qo(d,"ytp-ce-subscribe-button");if(a.player.V().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.vS(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={G:"div",Ia:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-expanding-overlay",W:[{G:"div",K:"ytp-ce-expanding-overlay-hider"},{G:"div",K:"ytp-ce-expanding-overlay-background"},{G:"div",K:"ytp-ce-expanding-overlay-content",W:[{G:"div",K:"ytp-ce-expanding-overlay-body",
W:[{G:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",K:"ytp-ce-website-title",X:{dir:g.Go(b.title||"")},qa:b.title},{G:"div",K:"ytp-ce-website-metadata",qa:b.metadata},{G:"a",Ia:["ytp-ce-website-goto","ytp-ce-link"],X:{href:j4(a,b.Bt),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",K:"ytp-ce-expanding-image",X:i4(b)},{G:"div",K:"ytp-ce-expanding-icon",X:sab(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",K:"ytp-ce-merchandise-price-container",
W:[{G:"div",K:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({G:"div",K:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={G:"div",Ia:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.uA||"","aria-hidden":"true"},W:[{G:"div",K:"ytp-ce-element-shadow"},{G:"div",K:"ytp-ce-expanding-overlay",W:[{G:"div",K:"ytp-ce-expanding-overlay-hider"},{G:"div",K:"ytp-ce-expanding-overlay-background"},{G:"div",K:"ytp-ce-expanding-overlay-content",
W:[{G:"div",K:"ytp-ce-expanding-overlay-body",W:[{G:"div",K:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",K:"ytp-ce-merchandise-title",X:{dir:g.Go(b.title||"")},qa:b.title},c,{G:"div",K:"ytp-ce-merchandise-metadata",qa:b.metadata},{G:"a",Ia:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:j4(a,b.Bt),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",K:"ytp-ce-expanding-image",X:i4(b)},{G:"div",K:"ytp-ce-merchandise-invideo-cta-container",W:[{G:"div",K:"ytp-ce-merchandise-invideo-cta",
qa:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.qo(c.element,"ytp-ce-placeholder");return c},i4=function(a){if(a.lS)var b=a.lS.thumbnails;
return sab(b?b[b.length-1].url:null)},sab=function(a){return a?{style:"background-image: url("+a+")"}:{}},rab=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.qo(b.element,"ytp-ce-force-expand"),k4(a,c.id,!0)):(g.so(b.element,"ytp-ce-force-expand"),g.so(b.element,"ytp-ce-element-hover"),k4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){tab(a,b,c)});
b.Qa("mouseleave",function(){uab(a,b,c)});
a.player.V().u||b.Qa("click",function(){g.qo(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){vab(a,c,m)});
b.Qa("keypress",function(m){vab(a,c,m)});
b.Qa("focus",function(){tab(a,b,c)});
b.Qa("blur",function(){uab(a,b,c)});
b.Qa("touchstart",function(){tab(a,b,c)});
var l=g.ze("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.so(b.element,"ytp-ce-element-hover");g.so(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.ze("ytp-sb-subscribe",b.element));d(g.ze("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},vab=function(a,b,c){if(b.Bt&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.po(d,"ytp-ce-element");){g.po(d,"subscribe-label")&&wab(a,b);
if(g.po(d,"ytp-ce-channel-subscribe"))return;d=g.Oe(d)}if(!d||g.po(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])uab(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.Q7)wab(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Kd(j4(a,b.Bt)),g.mL(g.Hd(c),void 0,b.sessionData);else{var e=g.kI(a.player.V())||a.player.getVideoData().D,f=function(){var h=j4(a,b.Bt),l=b.sessionData,m=b.watchEndpoint,n=g.jw(h);e&&n&&(n.v||n.list)?a.player.Ln(n.v,
l,n.list,!1,void 0,m||void 0):g.kL(h,l)};
wab(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},j4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.tI(a)+b}else return"";return b},tab=function(a,b,c){g.po(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.qo(b.element,"ytp-ce-element-hover"):a.player.V().u?(new g.io(function(){g.qo(b.element,"ytp-ce-element-hover")},200)).start():g.qo(b.element,"ytp-ce-element-hover"),l4(a,c.I2),k4(a,c.id,!0))},uab=function(a,b,c){g.so(b.element,"ytp-ce-element-hover");
g.so(b.element,"ytp-ce-force-expand");k4(a,c.id,!1)},k4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.uo(a.j[e].element,"ytp-ce-element-shadow-show",c)},l4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||g4(a))c&&c();else{b=xab(a,b);var e=0,f=!1,h=new g.io(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.hz(b[a],d)}},wab=function(a,b,c){l4(a,b.clickUrls,c);
(a=g.sC())&&b.T2&&g.FM(a,b.visualElement)},xab=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(yab(b[d],c));return a},yab=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},zab=function(a){return"string"===typeof a?a:""},m4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Aab=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},n4=function(a){return a.value?a.value:null},o4=function(a){if(!a)return null;
var b=g.Kd(zab(a.value));b=g.Hd(b);if(!b)return null;var c=m4(a.target,Bab,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Aab(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Cab=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Fab=function(a){if(!a)return null;
var b=m4(a.type,Dab),c=m4(a.trigger,Eab);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=o4(a?a:null);return b?new Cab(b,c,a):null},Gab=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Hab=function(a,b){return g.ib(a.action,b)},Iab=function(a,b){this.context=a;
this.j=b},Jab=function(a){return a.customMessage?p4("div","iv-card-message",a.customMessage):""},q4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",K:"iv-card-image",X:{style:a},W:c}},Kab=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(p4("li","",c.value));return{G:"ul",K:"iv-card-meta-info",W:b}},p4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Go(c);return{G:a,X:b,qa:c}},Lab=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.EA&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.EA+");");c.dir=g.Go(a.customMessage);var d=[{G:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",K:"iv-card-link-icon"}));return{G:"div",Ia:b,X:c,W:d}},r4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Oi.click,5)}},Mab=function(a,b){this.merchant=a;
this.price=b},Nab=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Oab=function(a,b){return b?b:Nab(a)?"current":"new"},s4=function(a,b){g.D.call(this);
var c=this;this.element=a;this.context=b;this.wb=!1;this.Xa=new Map;this.bb=new Map;this.context.F.addEventListener(g.MB("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.NB("annotations_module"),function(d){(d=c.bb.get(d))&&d.apply(c)})},t4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.kI(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.wb=!1});
a.context.j.Qa(b,"touchmove",function(){a.wb=!0})},Pab=function(a){var b;
return(null==(b=g.M(a,g.nJ))?0:b.url)?g.M(a,g.nJ).url:(a=g.M(a,g.lJ))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},u4=function(a,b,c){return{DT:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
VW:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
sH:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Qab=function(a,b,c){s4.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.Ra=this.Rb=this.B=this.isInitialized=!1;this.ya=null;this.cards=[];this.Hb=this.T=this.Ma=this.D=this.Sa=this.j=null;this.ma=[];this.oa=this.J=this.Wf=this.Ka=null;this.I=0;this.Fa=new g.io(function(){},c.Z.dh?4E3:3E3);
g.E(this,this.Fa);this.kb=new g.io(function(){});
g.E(this,this.kb);this.Aa=new Iab(c,function(e,f,h,l,m,n){t4(d,e,f,h,l,m,n)});
this.Y=new g.U({G:"div",K:"iv-drawer",X:{id:"iv-drawer"},W:[{G:"div",K:"iv-drawer-header",X:{"aria-role":"heading"},W:[{G:"span",K:"iv-drawer-header-text"},{G:"button",Ia:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",K:"iv-drawer-content"}]});g.E(this,this.Y);this.C=this.Y.element;this.ib=new g.lO(this.Y,330);g.E(this,this.ib);this.Tb=g.ze("iv-drawer-header-text",this.C);this.u=g.ze("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&v4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.B)&&w4(d)});
this.F.addEventListener("videodatachange",this.ws.bind(this))},Rab=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){v4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){w4(a)});
var c=b.headerText;g.Qe(a.Tb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ka=g.oC(b.trackingParams);a.J=g.oC(b.closeTrackingParams);a.Wf=g.oC(b.iconTrackingParams)},Sab=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.F.V().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.UB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Oi:{},xo:null,Uk:e.trackingParams?g.oC(e.trackingParams):null,Wf:f&&f.trackingParams?g.oC(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
EA:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};x4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.UB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:y4(a,c,b,f),sponsored:!1,Oi:u4(f,e,f.command),xo:f.trackingParams?g.oC(f.trackingParams):null,Uk:e.trackingParams?g.oC(e.trackingParams):null,Wf:l&&l.trackingParams?g.oC(l.trackingParams):null,imageUrl:z4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.UB(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,EA:null,title:f.title?g.UB(f.title):"",customMessage:f.callToAction?g.UB(f.callToAction):"",url:g.M(f.command,g.nJ).url?o4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.M(f.command,g.nJ).url}):null,onClickCommand:null};x4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.UB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:y4(a,c,b,e),sponsored:!1,Oi:u4(e,f,e.endpoint),xo:e.trackingParams?g.oC(e.trackingParams):null,Uk:f.trackingParams?g.oC(f.trackingParams):null,Wf:l&&l.trackingParams?g.oC(l.trackingParams):null,channelId:g.M(e.endpoint,A4).browseId,customMessage:e.customText?g.UB(e.customText):null,PV:z4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.UB(e.channelName):"",metaInfo:[e.subscriberCountText?g.UB(e.subscriberCountText):""],url:o4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.M(e.endpoint,A4).canonicalBaseUrl?g.M(e.endpoint,A4).canonicalBaseUrl:"/channel/"+g.M(e.endpoint,A4).browseId}),onClickCommand:null};x4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.UB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:y4(a,c,b,e),sponsored:!1,Oi:u4(e,f,e.action),xo:e.trackingParams?g.oC(e.trackingParams):null,Uk:f.trackingParams?g.oC(f.trackingParams):null,Wf:l&&l.trackingParams?g.oC(l.trackingParams):null,sD:z4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.UB(e.customMessage):null,playlistVideoCount:g.UB(e.playlistVideoCount),title:e.playlistTitle?g.UB(e.playlistTitle):"",metaInfo:[e.channelName?g.UB(e.channelName):
"",e.videoCountText?g.UB(e.videoCountText):""],url:o4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Pab(e.action)}),onClickCommand:null};x4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.UB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:y4(a,c,b,e),sponsored:!1,Oi:u4(e,f,e.action),xo:e.trackingParams?g.oC(e.trackingParams):null,Uk:f.trackingParams?g.oC(f.trackingParams):null,Wf:l&&l.trackingParams?g.oC(l.trackingParams):null,sD:z4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.UB(e.lengthString):null,customMessage:e.customMessage?g.UB(e.customMessage):null,title:e.videoTitle?g.UB(e.videoTitle):"",metaInfo:[e.channelName?g.UB(e.channelName):
"",e.viewCountText?g.UB(e.viewCountText):""],isLiveNow:!!e.badge,url:o4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Pab(e.action)}),onClickCommand:null};x4(a,b)}}}}}a.I++},z4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},y4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Vab=function(a,b){if(b=Uab(a,b))b===a.j&&(a.j=null),a.F.removeCueRange(b.eg.id),g.Ne(b.PJ),g.ob(a.cards,b),a.rE(),B4(a)},v4=function(a,b,c){if(!a.B){a.ib.show();
a.Sa=new g.io(function(){g.qo(a.context.F.getRootNode(),g.KW.IV_DRAWER_OPEN)},0);
a.Sa.start();a.ya=g.yz(a.u,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.sC();d&&a.Ka&&a.J&&g.DM(d,[a.Ka,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.nU||(f.nU=!0,Wab(a.context.logger,f.eg.Oi.DT,b)),d&&g.DM(d,[f.eg.xo]);Y3(a.F);c&&(a.D=new g.io(function(){a.Ma=a.T;a.Hb.focus()},330),a.D.start())}},w4=function(a){a.B&&(a.ib.hide(),g.zz(a.ya),a.ya=null,g.so(a.context.F.getRootNode(),g.KW.IV_DRAWER_OPEN),a.B=!1,Y3(a.F),a.D&&a.D.stop(),a.D=new g.io(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.D.start())},Yab=
function(a){g.ro(a.vb(),[g.KW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.IQ(a.F,a.C,5);Xab(a);a.T=g.ze("ytp-cards-button",a.F.getRootNode());a.Hb=g.ze("iv-drawer-close-button",a.C);a.isInitialized=!0},Xab=function(a){var b=g.ze("iv-drawer-close-button",a.C);
a.context.j.Qa(b,"click",a.S0,a);a.context.j.Qa(a.u,"touchend",function(){a.Fa.start()});
a.context.j.Qa(a.u,"scroll",a.j1,a);a.context.u.subscribe("onHideControls",function(){a.Ra=!0});
a.context.u.subscribe("onShowControls",function(){a.Ra=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ra=g.po(a.F.getRootNode(),"ytp-autohide")});
a.ma.push(g.Sz("iv-button-shown",a.f3,a));a.ma.push(g.Sz("iv-button-hidden",a.e3,a));a.ma.push(g.Sz("iv-teaser-shown",a.yY,a));a.ma.push(g.Sz("iv-teaser-hidden",a.g3,a));a.ma.push(g.Sz("iv-teaser-clicked",a.xY,a))},Zab=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.M(b.onClickCommand,g.b8a))?void 0:c.targetId)?(a.oa=b,!0):!1},$ab=function(a,b){a.oa=b;
var c=a.F.getVideoData();if(!c)return!1;c=a.F.N("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.pJ(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.M(h[0],g.rNa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}return!1},
x4=function(a,b){if(!Zab(a,b)||$ab(a,b)){var c=abb(a,b);
if(c){var d={eg:b,PJ:c.element,nU:!1};if(!b.onClickCommand){a.isInitialized||Yab(a);Vab(a,b.id);var e=bbb(a,d);g.yb(a.cards,e,0,d);c.Da(a.u,e);a.rE()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,B4(a),cbb(a,d),v4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&dbb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){dbb(a,d)}),B4(a))}}},abb=function(a,b){switch(b.type){case "simple":var c=a.Aa;
var d=b.displayDomain?{G:"div",K:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=Lab(b);d={G:"div",Ia:["iv-card"],W:[{G:"a",K:"iv-click-target",X:{href:b.url?n4(b.url)||"":""},W:[q4(b.imageUrl,d),{G:"div",K:"iv-card-content",W:[p4("h2",void 0,b.title),e]}]}]};d=new g.U(d);r4(c,g.ye("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.Aa;d={G:"div",Ia:["iv-card","iv-card-channel"],W:[{G:"a",Ia:["iv-click-target"],X:{href:n4(b.url)||"","data-ytid":b.channelId},W:[q4(b.PV),{G:"div",
K:"iv-card-content",W:[Jab(b),{G:"h2",K:"iv-card-primary-link",qa:b.title},Kab(b)]}]}]};d=new g.U(d);r4(c,g.ye("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.Aa;d={G:"div",Ia:["iv-card","iv-card-playlist"],W:[{G:"a",K:"iv-click-target",X:{href:n4(b.url)||""},W:[q4(b.sD,{G:"div",K:"iv-card-image-overlay",W:[{G:"span",K:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{G:"div",K:"iv-card-content",W:[Jab(b),p4("h2","iv-card-primary-link",b.title),Kab(b)]}]}]};d=new g.U(d);
r4(c,g.ye("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.Aa;var f=!g.lb(b.offers);d=["iv-card"];e="";var h=Lab(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({G:"div",K:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({G:"div",K:"iv-card-offer-merchant",qa:h.merchant}),h={G:"div",W:f});f=b.url?n4(b.url)||"":"";d={G:"div",Ia:d,X:{tabindex:"0"},W:[{G:"a",Ia:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{G:"div",K:"iv-card-content",W:[b.sponsored?{G:"div",K:"iv-card-sponsored",W:["Sponsored",{G:"div",K:"iv-ad-info-container",W:[{G:"div",K:"iv-ad-info",qa:"{{adInfo}}"},{G:"div",K:"iv-ad-info-icon-container",W:[{G:"div",K:"iv-ad-info-icon"},{G:"div",K:"iv-ad-info-callout"}]}]}]}:"",{G:"a",K:"iv-click-target",X:{href:f},W:[p4("h2",e,b.title),h]}]}]};d=new g.U(d);e=g.Fe("span");g.Qe(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.xe(e,"adInfo");r4(c,g.ye("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.Aa;d=b.videoDuration?{G:"span",K:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{G:"span",Ia:["yt-badge","yt-badge-live"],qa:"LIVE NOW"}:null;f={G:"div",Ia:["iv-card","iv-card-video"],W:[{G:"a",K:"iv-click-target",X:{href:(null==(h=b.url)?void 0:n4(h))||""},W:[q4(b.sD,d),{G:"div",K:"iv-card-content",W:[Jab(b),p4("h2","iv-card-primary-link",b.title),Kab(b),e]}]}]};d=new g.U(f);r4(c,g.ye("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.F.V().experiments.jb("web_rounded_containers")&&g.qo(b.element,"ytp-rounded-info");return b},bbb=function(a,b){if(0===a.cards.length)return 0;
a=g.jb(a.cards,function(c){return b.eg.startMs>c.eg.startMs||b.eg.startMs===c.eg.startMs&&b.eg.timestamp>=c.eg.timestamp?!0:!1});
return-1===a?0:a+1},ebb=function(a){return a.j?"productListing"===a.j.eg.type:g.Nk(a.cards,function(b){return"productListing"===b.eg.type})},B4=function(a){g.uo(a.F.getRootNode(),"ytp-cards-shopping-active",ebb(a))},dbb=function(a,b){if(!g.po(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.sC(),d=a.j?a.j.eg.Wf:a.Wf;
c&&d&&g.EM(c,[d]);a.j=b;B4(a)}(c=a.isInitialized&&"none"==a.vb().style.display)||(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=!(1===c||3===c||d));c||b.eg.teaserDurationMs&&a.F.lz(!0,{teaserText:b.eg.teaserText,durationMs:b.eg.teaserDurationMs,onClickCommand:b.eg.onClickCommand});a.kb.isActive()||((!a.B||!a.Fa.isActive()&&a.Ra)&&cbb(a,b),a.kb.start(910+b.eg.teaserDurationMs))}},cbb=function(a,b){a.Y.ub?(b=new c4([0,
a.u.scrollTop],[0,b.PJ.offsetTop],600,cab),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.yN(a.Y,!0),a.u.scrollTop=b.PJ.offsetTop,g.yN(a.Y,!1))},C4=function(a){return a.j&&a.j.eg?a.j.eg:a.cards[0]&&a.cards[0].eg?a.cards[0].eg:null},Uab=function(a,b){return g.ib(a.cards,function(c){return c.eg.id===b})},D4=function(a,b,c){s4.call(this,a,b);
this.annotation=c;this.isActive=!1},fbb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},E4=function(a,b,c){D4.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},gbb=function(a,b){var c=void 0===c?0:c;
var d=aab(b).width;g.Kl(b,d);c=new iab(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,bab);g.E(a,c);a.context.B.Qa(c,"begin",function(){g.Ql(b,!0)});
c.play()},jbb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ia:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({G:"div",Ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.vS(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.F),a.j.Da(d));var f=a.createElement({G:"div",Ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ia:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Ql(h,!1);a.context.Z.N("web_rounded_containers")&&g.qo(h,"ytp-rounded-branding-context");var l=a.createElement({G:"div",Ia:["branding-context-container-outer"]});l.appendChild(h);g.yl(l,"right",b.image_width+"px");g.Ke(a.vb(),l);a.B=new g.io(function(){hbb(a,h,l)},500);
g.E(a,a.B);a.context.j.Qa(a.vb(),"mouseover",function(){ibb(a,h,l,f,b.image_height)});
a.context.j.Qa(a.vb(),"mouseout",function(){a.B.start()})}},ibb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Pl(b);a.j||(b.style.width=g.Jl(f.width,!0),c.style.width=g.Jl(f.width,!0));g.yl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.yl(d,"right","1px");a.C=!0;g.Ql(b,!0);a.D=new g.io(function(){g.qo(this.vb(),"iv-branding-active")},0,a);
a.D.start()}},hbb=function(a,b,c){g.so(a.vb(),"iv-branding-active");
a.I=new g.io(function(){g.Ql(b,!1);a.j||(c.style.width=g.Jl(0,!0))},250);
a.I.start();a.C=!1},kbb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.F=f;this.u=h},lbb=function(a,b,c){D4.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.Y=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({G:"div",Ia:["iv-promo-contents"]});this.D=new g.io(function(){d.j.setAttribute("aria-hidden","true");g.Ql(d.B,!1);g.Ql(d.u,!0)},700,this);
g.E(this,this.D)},nbb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.vb().setAttribute("aria-hidden","true");a.vb().setAttribute("aria-label","Promotion");a.vb().tabIndex=0;var e=a.annotation.bf(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",K:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",K:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&t4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",K:"iv-promo-txt"}),g.Ud(f,n4(e)),a.j=f):a.j=a.createElement({G:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_1}]});
var m=a.createElement({G:"p",W:[{G:"span",K:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ia:["iv-button","iv-promo-button"],W:[{G:"span",K:"iv-button-content",qa:f}]});var p=a.createElement({G:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&t4(a,a.vb(),e,a.annotation.id,b.session_data,void 0,c)}g.qo(a.j,"iv-click-target");
e&&t4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",W:[{G:"span",qa:b.text_line_1}]}),m=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ia:["yt-badge","iv-promo-badge-live"],qa:"LIVE NOW"})),g.qo(a.j,"iv-click-target"),e&&t4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({G:"div",K:"iv-promo-actions"});a.u=a.createElement({G:"button",Ia:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Qa(a.u,"click",function(q){mbb(a,5E3,q)});
c.appendChild(a.u);g.Ql(a.u,!1);a.context.j.Qa(a.vb(),"mouseover",a.h2,a);a.context.j.Qa(a.vb(),"mouseout",a.g2,a);a.context.j.Qa(a.vb(),"touchend",function(q){mbb(a,5E3,q)});
a.B=a.createElement({G:"button",Ia:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.b2:a.Z1,a);c.appendChild(a.B);g.ro(a.vb(),d);h&&(g.Ke(a.vb(),h),n&&h.appendChild(n));g.Ke(a.vb(),a.J);g.Ke(a.vb(),c)},mbb=function(a,b,c){c.stopPropagation();
obb(a);pbb(a,b);a.j.focus()},qbb=function(a){a.isCollapsed||a.T||a.C||(g.qo(a.vb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},obb=function(a){a.D.stop();
a.isCollapsed&&(g.to(a.vb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ql(a.u,!1),g.Ql(a.B,!0))},pbb=function(a,b){a.C||(a.C=g.sf(function(){rbb(this);
qbb(this)},b,a))},rbb=function(a){a.C&&(g.Da.clearTimeout(a.C),a.C=null)},sbb=function(a){this.F=a},Wab=function(a,b,c){b&&(c?F4(a,b.map(function(d){return g.ao(d,c)})):F4(a,b))},F4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.hz(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},tbb=function(a){g.rR.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new sbb(this.player);this.D=new g.OF(this);this.C=this.rp=null;this.events=new g.OF(this);this.J=this.j=null;this.T=[];g.E(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.D.S(this.player,"resize",function(d){b.ea("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.zY,this);this.subscribe("resize",this.oG,this);this.player.V().ya.subscribe("vast_info_card_add",this.xV,this);g.E(this,this.events);this.Y=this.createElement({G:"div",K:"video-custom-annotations"});this.u=new g.U({G:"div",Ia:["ytp-player-content","ytp-iv-player-content"]});g.E(this,this.u);g.IQ(this.player,this.u.element,4);this.u.hide();this.B=new g.U({G:"div",Ia:["ytp-iv-video-content"]});g.E(this,this.B);a=this.createElement({G:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Vv()&&this.load();var c=this.createElement({G:"style"});(g.we("HEAD")[0]||document.body).appendChild(c);g.bb(this,function(){g.Ne(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},ubb=function(a){a=a.createElement({G:"div",
Ia:["annotation","annotation-type-custom"]});g.Ql(a,!1);return a},vbb=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.yN(a.u,b);g.yN(a.B,b)},wbb=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ia(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(wbb(a,e))}return c},Abb=function(a){var b=a.player.getVideoData();
if(b.Sa){var c=a.player.V().ya.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.rw(h)&&h.responseXML?h.responseXML:null)&&xbb(a,h)}};
g.Cx()&&(d.onFinish=ybb(a,d.onFinish));d.postParams={ic_only:"1"};zbb(d,c);g.yw(b.Sa,d)}}},zbb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.GA&&(a.postParams.ic_coll=b.GA);b.xE&&(a.postParams.ic_xml=b.xE);b.vD&&(a.postParams.ic_track=b.vD)},Bbb=function(a){var b=new g.U({G:"div"});
g.Ql(b.element,!1);var c=new Qab(a.player,b.element,G4(a));g.E(c,b);b.Da(a.u.element);c.gD();return c},G4=function(a){if(!a.J){var b=new jab(a);
g.E(a,b);var c=new g.Fj(a);g.E(a,c);a.J=new kbb(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Dj)}return a.J},xbb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.sC();if(e){var f=g.rC();f&&g.dw(g.NDa)(void 0,e,f,[g.oC(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=wbb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=m4(f.type,Cbb),p=m4(f.style,Dbb),q=zab(f.data),r=0!==q.length?JSON.parse(q):{};var w=f.action;f=Fab;if(null==w)var x=null;else if(g.Ha(w)){l=[];for(var z=g.t(w),B=z.next();!B.done;B=z.next()){var C=f(B.value);
C&&l.push(C)}x=l}else{var G=f(w);x=G?[G]:[]}e=m&&n?new Gab(m,n,p,x,r):null}else e=null}catch(V){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=ubb(f),K=null;switch(l.type){case "branding":if(f.player.V().Rd)break;f.u.element.appendChild(F);K=new E4(F,G4(f),l);break;case "promotion":g.IQ(f.player,F,4),K=new lbb(F,G4(f),l)}K&&K.gD();if(f=K)g.E(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Bbb(a),g.E(a,a.j));if("card"===e.type){c=a.j;var P=e&&e.data&&e.data.card_type;
f=e.data;if(P)switch(l=f.tracking||{},l={DT:l.impression,click:l.click,close:l.close,VW:l.teaser_impression,sH:l.teaser_click},F=f.tracking_params||{},K=null,P){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,xo:F.card?g.oC(F.card):null,Uk:F.teaser?g.oC(F.teaser):null,Wf:F.icon?g.oC(F.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,PV:f.image_url,title:f.title,metaInfo:f.meta_info,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};x4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,xo:F.card?g.oC(F.card):null,Uk:F.teaser?
g.oC(F.teaser):null,Wf:F.icon?g.oC(F.icon):null,sD:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};x4(c,e);break;case "productListing":f.signin_url&&(K=o4({target:"current",value:f.signin_url}));P=[];for(var Q=f.offers||[],Y=0;Y<Q.length;Y++)P.push(new Mab(g.oe(Q[Y].merchant),g.oe(Q[Y].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,xo:F.card?g.oC(F.card):null,Uk:F.teaser?g.oC(F.teaser):null,Wf:F.icon?g.oC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,EA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),nfb:K,mfb:f.signin_title?f.signin_title:void 0,lfb:f.signin_message?f.signin_message:void 0,offers:P,onClickCommand:null};x4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,xo:F.card?g.oC(F.card):null,Uk:F.teaser?
g.oC(F.teaser):null,Wf:F.icon?g.oC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,EA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};x4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Oi:l,xo:F.card?g.oC(F.card):null,Uk:F.teaser?g.oC(F.teaser):null,Wf:F.icon?g.oC(F.icon):null,sD:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:o4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},x4(c,e)}}else Rab(a.j,e);c=!0}}c&&
(Y3(a.player),a.oG())},Ebb=function(a,b){var c=!1;
a.j||(a.j=Bbb(a),g.E(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Sab(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.UB(b.headerText):"",g.Qe(c.Tb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ka=b.trackingParams?g.oC(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.oC(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Wf=b.icon.infoCardIconRenderer.trackingParams?
g.oC(b.icon.infoCardIconRenderer.trackingParams):null,Y3(a.player),a.oG())},Fbb=function(a,b,c,d,e){if(!a.player.V().Rd){var f=[];
b.navigationEndpoint&&g.M(b.navigationEndpoint,A4)&&g.M(b.navigationEndpoint,A4).browseId&&f.push(new Cab("openUrl","click",new Aab("/channel/"+g.M(b.navigationEndpoint,A4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.M(b.subscribeButton,
g.lK)){d.channel_id=g.M(b.subscribeButton,g.lK).channelId;var l;b=g.M(b.subscribeButton,g.lK);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.UB(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.UB(b.subscriberCountText))):(b.subscriberCountText&&(e=g.UB(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.UB(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.M(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.T2))?void 0:m.url)||"";l={subscribeText:g.UB(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.UB(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Gab(c,"branding","branding",f,d);l=ubb(a);a.u.element.appendChild(l);f=new E4(l,G4(a),f);f.gD();g.E(f,f);a.I[c]=f}},ybb=function(a,b){return function(){var c=g.xa.apply(0,arguments);
a.isDisposed()||a.T.push(g.eo.zi(function(){b.apply(null,g.u(c))}))}},Gbb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.BQ.prototype.lz=g.ca(18,function(a,b){var c=g.JR(this.tb());c&&c.lz(a,b)});
var $3={},a4=null;g.Ra(c4,g.Co);g.k=c4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Zc())return!1;b4(this);this.startTime=a=g.Qa();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.kG();this.Cl("play");-1==this.j&&this.Cl("resume");this.j=1;var b=g.Ka(this);b in $3||($3[b]=this);eab();fab(this,a);return!0};
g.k.stop=function(a){b4(this);this.j=0;a&&(this.progress=1);gab(this,this.progress);this.Cl("stop");this.zq()};
g.k.pause=function(){this.Zc()&&(b4(this),this.j=-1,this.Cl("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Cl("destroy");c4.Df.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.jI=function(){this.Cl("animate")};
g.k.Cl=function(a){this.dispatchEvent(new hab(a,this))};
g.Ra(hab,g.eb);g.Ra(d4,c4);d4.prototype.C=function(){};
d4.prototype.jI=function(){this.C();d4.Df.jI.call(this)};
d4.prototype.zq=function(){this.C();d4.Df.zq.call(this)};
d4.prototype.kG=function(){this.C();d4.Df.kG.call(this)};
g.Ra(iab,d4);iab.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var A4=new g.Pp("browseEndpoint");g.v(jab,g.D);g.k=jab.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.yz(a,b,c);this.j.push(a);return a};
g.k.QF=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.Fqa(a,b,c);this.j.push(a);return a};
g.k.Ec=function(a){g.zz(a);g.ob(this.j,a)};
g.k.cg=function(){g.zz(this.j);this.j.length=0};
g.k.ra=function(){this.cg();g.D.prototype.ra.call(this)};g.v(mab,g.rR);g.k=mab.prototype;g.k.load=function(){g.rR.prototype.load.call(this);if(!g4(this)){var a=g.hCa(this.player.getVideoData());a?(a=lab(a,nab(this)),h4(this,a,!1)):oab(this)}};
g.k.unload=function(){h4(this,null);this.B&&(this.B.abort(),this.B=null);g.rR.prototype.unload.call(this)};
g.k.rh=function(a,b){return g4(this)?"loadCustomEndscreenRenderer"===a?(a=lab(b,"new"),h4(this,a),!0):null:null};
g.k.getOptions=function(){return g4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Db=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Hbb.length;f++){var h=Math.abs(b.width-Hbb[f]);if(-1===e||d>=h)e=f,d=h}d=Ibb[e];this.u&&g.yl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ol(e.element,m,f);g.Kl(e.element,n,p);this.ma&&(g.to(e.element,Jbb),256<m||256<f?g.qo(e.element,"ytp-ce-large-round"):96<m||96<f?g.qo(e.element,"ytp-ce-medium-round"):g.qo(e.element,"ytp-ce-small-round"));g.to(e.element,Kbb);m=h.left+h.width/2;h=h.top+l/2;g.qo(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.to(e.element,Ibb);g.qo(e.element,d);(e=g.xe(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.yl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())l4(this,this.endscreen.impressionUrls),(a=g.sC())&&this.endscreen.visualElement&&g.CM(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.qo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.qo(b,"ytp-ce-shown");l4(this,c.impressionUrls);(b=g.sC())&&g.CM(b,c.visualElement);this.player.V().I&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.so(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.so(b,"ytp-ce-shown");this.player.V().I&&this.player.Oa("endscreenelementhidden",a)}};
g.k.D6=function(a){var b=this;a.target===window&&(new g.io(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.to(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Hbb=[346,426,470,506,570,640,853,1280,1920],Ibb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Kbb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Jbb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Bab={rpa:"current",kOa:"new"};var Dab={CLOSE:"close",XRa:"openUrl",SUBSCRIBE:"subscribe"},Eab={kka:"click",CLOSE:"close",Hza:"hidden",xXa:"rollOut",yXa:"rollOver",LZa:"shown"};Gab.prototype.bf=function(){var a=Hab(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Dbb={Cfa:"anchored",YX:"branding",CHANNEL:"channel",hpa:"cta",Kza:"highlightText",SDa:"label",PLAYLIST:"playlist",QUa:"popup",v1a:"speech",SUBSCRIBE:"subscribe",C4a:"title",VIDEO:"video",qab:"website"},Cbb={YX:"branding",kia:"card",Bra:"drawer",Jza:"highlight",EJa:"marker",ZVa:"promotion",TEXT:"text",Wbb:"widget"};g.v(s4,g.D);g.k=s4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.KB(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.bb.set(a,e);this.context.F.Pe([a])};
g.k.gD=function(){this.context.u.subscribe("resize",this.rE,this)};
g.k.vb=function(){return this.element};
g.k.kI=function(a,b,c,d,e,f){if(this.wb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ne(this.vb())};
g.k.rE=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=n4(a);if(f){var h=Oab(f,a.target),l=function(){a.j&&e.context.F.pauseVideo();var m=e.context.videoData.D||!1,n=g.jw(f||"");m&&n&&(n.v||n.list)?e.context.F.Ln(n.v,b,n.list,!1):g.mL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);F4(this.context.logger,c,l,d);Nab(f)||(c=g.sC(),d=b.itct,c&&d&&g.FM(c,g.oC(d)))}};
g.k.ra=function(){this.Xa.clear();this.bb.clear();g.D.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.E(this,a);return a.element};g.v(Qab,s4);g.k=Qab.prototype;g.k.ws=function(){this.oa&&x4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.Pl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.rE=function(){var a=this.isAvailable();g.Ql(this.vb(),a);g.uo(this.context.F.getRootNode(),g.KW.IV_DRAWER_ENABLED,a);Y3(this.F)};
g.k.destroy=function(){this.F.lz(!1);try{this.F.getRootNode().removeChild(this.C)}catch(a){}g.Tz(this.ma);g.zz(this.ya);this.Sa&&this.Sa.dispose();this.D&&this.D.dispose();s4.prototype.destroy.call(this)};
g.k.S0=function(){if(this.B){F4(this.context.logger,C4(this).Oi.close);var a=g.sC();a&&this.J&&g.FM(a,this.J);w4(this)}};
g.k.j1=function(){g.uo(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.f3=function(){var a=g.sC(),b=C4(this);b=b?b.Wf:this.Wf;a&&b&&g.DM(a,[b])};
g.k.e3=function(){var a=g.sC(),b=C4(this);b=b?b.Wf:this.Wf;a&&b&&g.EM(a,[b])};
g.k.yY=function(){var a=C4(this);F4(this.context.logger,a.Oi.VW);var b=g.sC();b&&a&&g.DM(b,[a.Uk,a.Wf])};
g.k.g3=function(){var a=g.sC(),b=C4(this);a&&b&&g.EM(a,[b.Uk])};
g.k.xY=function(a){var b=C4(this),c=g.sC();this.j?a?(a=this.context.logger,F4(a,b.Oi.sH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Uk&&g.FM(c,b.Uk)):(a=this.context.logger,F4(a,b.Oi.sH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Wf&&g.FM(c,b.Wf)):(a=this.context.logger,F4(a,b.Oi.sH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.Wf&&g.FM(c,this.Wf))};g.v(D4,s4);D4.prototype.gD=function(){s4.prototype.gD.call(this);fbb(this)};
D4.prototype.show=function(){s4.prototype.show.call(this);var a=g.sC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.DM(a,[g.oC(b.itct)])};
D4.prototype.hide=function(){s4.prototype.hide.call(this);var a=g.sC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.EM(a,[g.oC(b.itct)])};g.v(E4,D4);
E4.prototype.show=function(){if(!this.isActive){D4.prototype.show.call(this);if(!this.J){g.qo(this.vb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ia:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ql(this.u,!1);var b=this.createElement({G:"button",Ia:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.vb().appendChild(b);var c=this.annotation.bf();c&&t4(this,b,
c,this.annotation.id,a.session_data);jbb(this,a);this.J=!0}g.Ql(this.vb(),!0);this.isActive=!0;this.u&&(gbb(this,this.u),g.qo(this.context.F.getRootNode(),"ytp-branding-shown"))}};
E4.prototype.hide=function(){this.isActive&&(D4.prototype.hide.call(this),g.Ql(this.vb(),!1),this.isActive=!1,g.so(this.context.F.getRootNode(),"ytp-branding-shown"))};
E4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);D4.prototype.destroy.call(this)};g.v(lbb,D4);g.k=lbb.prototype;g.k.show=function(){this.isActive||(D4.prototype.show.call(this),this.Y||(nbb(this),this.Y=!0),g.Ql(this.vb(),!0),g.sf(function(){g.so(this.vb(),"iv-promo-inactive")},100,this),this.vb().removeAttribute("aria-hidden"),this.isActive=!0,rbb(this),obb(this),pbb(this,this.I))};
g.k.hide=function(){this.isActive&&(g.qo(this.vb(),"iv-promo-inactive"),this.isActive=!1,this.vb().setAttribute("aria-hidden","true"))};
g.k.kI=function(a,b,c,d,e,f){return this.isCollapsed?!1:D4.prototype.kI.call(this,a,b,c,d,e,f)};
g.k.h2=function(a){this.T=!0;mbb(this,500,a)};
g.k.g2=function(){this.T=!1;qbb(this)};
g.k.Z1=function(a){a.stopPropagation();this.hide()};
g.k.b2=function(a){a.stopPropagation();rbb(this);this.isCollapsed=!0;g.qo(this.vb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();D4.prototype.destroy.call(this)};g.v(tbb,g.rR);g.k=tbb.prototype;g.k.rh=function(a,b){if(!Gbb(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.z5a(b))&&xbb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Vab(this.j,b),Y3(this.player)),!0}return null};
g.k.getOptions=function(){return Gbb(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Vv=function(){var a=this.player.V(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.D&&a.ma||a.N("embeds_enable_muted_autoplay")&&this.player.isMutedByMutedAutoplay()?!1:1===c&&!b.NQ||a.ya.get(b.videoId)||g.sK(b)||g.tK(b)?!0:!1};
g.k.oG=function(){if(this.B){var a=this.player.gb().getVideoContentRect(!0);g.Ol(this.B.element,a.width,a.height);g.Kl(this.B.element,a.left,a.top)}if(this.j){var b=this.player.wk();a=this.j;b=b.width;g.uo(a.C,"iv-drawer-small",426>=b);g.uo(a.C,"iv-drawer-big",1280<=b)}};
g.k.zY=function(a){vbb(this,a.state);g.T(a.state,2)&&(this.xj()&&this.uo()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.lz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.rw(h)&&h.responseXML?h.responseXML:null)&&(xbb(b,h),g.qo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.rR.prototype.load.call(this);vbb(this,this.player.Fb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Cx()&&(a=ybb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().ya.get(d);f&&zbb(e,f);f=f&&(f.xE||f.GA);if(!c.Qz||f)c.Sa?this.C=g.yw(c.Sa,e):(this.rp=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.rp));
g.IQ(this.player,this.B.element,4);this.oG();(f=g.sK(c))&&Ebb(this,f);(f=g.tK(c))&&f.featuredChannel&&Fbb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Sa&&(this.rp&&(this.player.removeEventListener("videodatachange",this.rp),this.rp=null),this.C=g.yw(b.Sa,a))};
g.k.unload=function(){this.player.dg("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,Y3(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.rR.prototype.unload.call(this);this.B.detach();this.rp&&(this.player.removeEventListener("videodatachange",this.rp),this.rp=null)};
g.k.xV=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Abb(this):this.load())};
g.k.xj=function(){return!!this.j&&this.j.isAvailable()};
g.k.uo=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.xj();this.j&&(a?c?v4(this.j,c,b):v4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):w4(this.j))};
g.k.lz=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().ya.unsubscribe("vast_info_card_add",this.xV,this);g.so(this.player.getRootNode(),g.KW.IV_DRAWER_OPEN);for(var a=this.T,b=g.eo,c=0,d=a.length;c<d;c++)b.Bm(a[c]);this.T.length=0;g.rR.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.E(this,a);return a.element};g.qR("annotations_module",tbb);g.qR("creatorendscreen",mab);})(_yt_player);
